apiVersion: v1
data:
  alertmanager.yml: |
    global: {}
    receivers:
    - name: default-receiver
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 3h
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-1650653727
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2022-04-22T18:55:28Z"
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-15.8.5
    component: alertmanager
    heritage: Helm
    release: prometheus-1650653727
  name: prometheus-1650653727-alertmanager
  namespace: default
  resourceVersion: "11954"
  uid: f6141c8a-e317-410e-a0ca-c6d5c0a0c0e4
